# requirements.yml
roles:
- include: requirements/immich.yml 
- include: requirements/k3s.yml
- include: requirements/other.yml
collections:
- name: community.kubernetes
- name: community.general
  version: "4.7.0"
- name: kubernetes.core
  version: "2.2.0"
- name: community.docker
