# Секретный ключ SSH (пример значения — замените на своё)
ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  -----END RSA PRIVATE KEY-----

# Параметры SSHFS (можно переопределять в inventory или vars)
immich_sshfs_user: "user"
immich_sshfs_host: "192.168.1.1"
immich_sshfs_remote_path: "/C:/Immich"
immich_sshfs_local_path: "/mnt/immich"
