---
- name: Установить MetalLB — применение манифеста
  k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml

- name: Ожидание создания namespace metallb-system
  wait_for:
    timeout: 120
    delay: 5
  register: wait_ns
  until: >
    (lookup('k8s', cluster_info='namespaces', namespace='metallb-system', kind='Namespace') is defined) or
    (wait_ns.elapsed > 120)

- name: Создать IPAddressPool для MetalLB
  k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      meta:
        name: default-pool
        namespace: metallb-system
      spec:
        addresses:
          - "{{ metallb_ip_range_start }}-{{ metallb_ip_range_end }}"

- name: Создать L2Advertisement
  k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      meta:
        name: default-adv
        namespace: metallb-system
      spec:
        ipAddressPools:
          - default-pool
