apiVersion: v1
kind: ConfigMap
meta
  name: seaweed-set-acl-script-{{ .Values.s3.identity }}

  set_acl.sh: |
    #!/bin/sh
    set -e

    IDENTITY="{{ .Values.s3.identity }}"
    BUCKET="{{ .Values.bucketAccess.bucket }}"
    PERMISSIONS='{{ toJson .Values.bucketAccess.permissions }}'

    echo "Setting permissions for $IDENTITY on bucket $BUCKET"

    ADMIN_ACCESS_KEY=$(cat /admin-secrets/accessKey)
    ADMIN_SECRET_KEY=$(cat /admin-secrets/secretKey)

    export AWS_ACCESS_KEY_ID="$ADMIN_ACCESS_KEY"
    export AWS_SECRET_ACCESS_KEY="$ADMIN_SECRET_KEY"
    export AWS_DEFAULT_REGION=us-east-1

    curl -X PUT "http://seaweedfs-master:9333/buckets/$BUCKET/acl" \
      -H "Content-Type: application/json" \
      -u "$ADMIN_ACCESS_KEY:$ADMIN_SECRET_KEY" \
      -d '{
          "user": "'$IDENTITY'",
          "permissions": '"$PERMISSIONS"'
        }'

    echo "Permissions applied."
