apiVersion: v1
kind: Secret
meta
  name: {{ printf "%s-s3-credentials" .Values.s3.identity }}
type: Opaque

  accessKey: {{ default (randAlphaNum 20) .Values.s3.accessKey | b64enc | quote }}
  secretKey: {{ default (randAlphaNum 40) .Values.s3.secretKey | b64enc | quote }}
