---
- name: Doker login
  gather_facts: no
  hosts: k3s
  tags: docker-login
  roles:
    - ghcr-login
  environment:
    K8S_AUTH_KUBECONFIG: "/home/ubuntu/.kube/config"
  become: yes

- name: Установка immich2
  gather_facts: no
  hosts: k3s
  tags: immich
  roles:
    - { role: 'immich2', tags: 'immich2'}
    - { role: 'redis', tags: 'redis'}
    - { role: 'postgresql', tags: 'postgresql'}
#    - { role: 'immich-db-migrate', tags: 'immich-db-migrate'}
  environment:
    K8S_AUTH_KUBECONFIG: "/home/ubuntu/.kube/config"
  become: yes
