---
- name: Doker login
  gather_facts: no
  hosts: k3s
  roles:
    - { role: 'ghcr-login', tags: 'docker-login'}
  environment:
    K8S_AUTH_KUBECONFIG: "/home/ubuntu/.kube/config"
  become: yes

- name: Установка metallb
  gather_facts: no
  hosts: k3s
  roles:
    - { role: 'metallb', tags: 'metallb'}
  environment:
    K8S_AUTH_KUBECONFIG: "/home/ubuntu/.kube/config"
  become: yes

- name: Установка immich2
  gather_facts: no
  hosts: k3s
  tags: immich-all
  vars_files:
    - "../inventories/group_vars/k3s.yml"
    - "../inventories/group_vars/s3.yml"
  roles:
    - { role: 'immich', tags: 'immich'}
    - { role: 'redis', tags: 'redis'}
    - { role: 'postgresql', tags: 'postgresql'}
  environment:
    K8S_AUTH_KUBECONFIG: "/home/ubuntu/.kube/config"
  become: yes

- name: Монтирование диска
  gather_facts: no
  hosts: k3s
  roles:
    - { role: 'mnt_disk', tags: 'mnt_disk'}
  environment:
    K8S_AUTH_KUBECONFIG: "/home/ubuntu/.kube/config"
  become: yes
