---
# defaults file for immich
# Значения по умолчанию
immich_namespace: immich
immich_version: "1.105.0"
immich_domain: photos.example.com

# Объём хранилища
immich_storage_size: 5Gi
immich_storage_class: local-path

# Ресурсы
immich_server_resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

immich_ml_resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

# Секреты БД
immich_db_user: immich
immich_db_password: "{{ 'immich-secret-password' | b64encode }}"  # base64-encoded
immich_db_name: immich
immich_db_host: immich-postgres
immich_db_port: "5432"
